version: 2
updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Japan
  open-pull-requests-limit: 10
