plugins:
  # Preset
  remark-preset-lint-sider: true

  # Rule
  remark-lint-first-heading-level: true
  "@mapbox/remark-lint-link-text": true
  remark-lint-code-block-syntax: true

  # NOTE: This is *not* a lint rule and does not have a severity.
  remark-validate-links: { root: ".", repository: "sider/sider-docs" }
