[build]

publish = "website/build/sider-docs"

command = "cd website && yarn install && yarn run build"

[[redirects]]
from = "/tools"
to = "/introduction#analysis-tools"

[[redirects]]
from = "/on-premises"
to = "/enterprise/releases"

[[redirects]]
from = "/on-premises/quick-start"
to = "/enterprise/quickstart"

[[redirects]]
from = "/on-premises/quick-start/*"
to = "/enterprise/quick-start/:splat"

[[redirects]]
from = "/enterprise/quick-start/setup"
to = "/enterprise/quickstart"

[[redirects]]
from = "/enterprise/quick-start/update"
to = "/enterprise/updating"
